services:
  - type: web
    name: itracker-be
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npx nest build
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
